### ISSUE TITLE
Select range of dates

### ISSUE THREAD

**Issue by wheelq** [BelkaLab/react-yearly-calendar#6]
How do I highlight/select/add class to a range of dates?
I would like to have a button, after clicking range of dates should be selected/highlighted. Is this possible?

**Comment by GiovanniFrigo** [comment]
Hi Michal! 
The features you request are planned to be added in the upcoming v1.1, coming sometime this week. You'll be able to both add a custom class to some dates/range of dates and to switch the selecting mode to select-range instead of select-single.

Watch the repo to be notified when I'll push that changes up!

**Comment by GiovanniFrigo** [comment]
This feature is now available in version 1.1.0 🎉
